### PR TITLE
Recommend spell checking

### PR DESCRIPTION
**Pull request by steffilazerte**
Every time I review a post I forget (or almost forget) to run a spell check. When I do run it, I nearly always find a typo. As running spell-check is a basic, but forgettable task I'd suggest adding it to the checklists (although I understand we don't want these lists getting too big!). 

If this is just my problem, forget the pull-request and I'll add it to my personal list :grin:

### CODE REVIEW

**Comment by stefaniebutland** [comment]
@steffilazerte what do you use to run a spell check?

**Comment by steffilazerte** [comment]
@stefaniebutland I use the one in RStudio: Either Edit > Check Spelling or F7 (but this only works when a .Rmd or .md document is open). I didn't specify because it'd depend on what editor people use, but perhaps it would be nice to point out that it's pretty straightforward in RStudio?

**Comment by maelle** [comment]
RStudio above some version, that it might make sense to mention (so people upgrade if needed)?

**Comment by maelle** [comment]
Cf #103 🙂

**Comment by steffilazerte** [comment]
Oh whoops, I didn't even think to look for issues. But while this new version of RStudio 1.3 introduces *real time* spell-checking, general spell checking has been around for quite a while, so I wouldn't think a version of RStudio would be needed

**Comment by maelle** [comment]
Oooh I see, thank you!

**Review by stefaniebutland — APPROVED** [review]

**Pull request merged**
