### PR TITLE
Doc Spanish tags

### PR DESCRIPTION
**Pull request by maelle**

### CODE REVIEW

**Comment by steffilazerte** [comment]
Looks good to me! Do we want to add this to the [checklists](https://blogguide.ropensci.org/editorchecklistpeer.html)? or is that getting out of control?

**Review by yabellini — COMMENTED** [review]
Looks good for me too.

**Comment by yabellini** [comment]
> Looks good to me! Do we want to add this to the [checklists](https://blogguide.ropensci.org/editorchecklistpeer.html)? or is that getting out of control?

On that list we have two tga related check: 
[ ] YAML subject tags are ok ("tech notes" for tech notes; "community" for non-staff non-editor)
[ ] YAML subject tags - software peer review, packagename
Would be something like this ?
[ ] YAML language tags are ok ("Español" and "Spanish" for blog post in this language)

**Comment by maelle** [comment]
In that case can you edit the PR directly?

**Comment by yabellini** [comment]
If anyone of you can tell me which file I should edit I will do it.  I see a checklist folder with some csv file, but the content in those files are not the same I see on the html.

**Comment by steffilazerte** [comment]
Hi Yani, the csv files are combined together to create the checklists (the `editor-checklist-peer-reviewed-pkg` is added to `editor-checklist`, etc.) The main ones to change would be `editor-checklist` as this should apply to both types of post and I'm not sure it needs to be on the author checklist.

I can also make this change, but wanted to check in, should language tags be in *their* language, i.e. use "Español" rather than Spanish? I think that makes sense, and if so, we should make this consistent with the use cases in the forum (which use English versions of the language name).

**Comment by yabellini** [comment]
Thanks for the explanation!. 
I think we need to use the word in the language of the post.  So _their_ language as you said. 
I'm trying to think why we would need to use the English name of the language and I can't think of anything.
Agree on being consistent in how we announce and show the language of our content.

**Comment by steffilazerte** [comment]
Okay, going with two tags for languages based on off-GitHub conversation with @yabellini. Rational (which I'm sure @maelle already concluded) is that we want these posts be found easily, so no matter how you search for it, you'll find it. Will help make sure English speakers also find the posts.

**Comment by steffilazerte** [comment]
And of course that's how the current blog posts are tagged 🤦🏼‍♀️. I really need to start looking into things first!

**Comment by maelle** [comment]
this is now outdated :tada:

**Pull request closed without merging**
